### ISSUE TITLE
Covid Vaccine Tracker using Deep Learning

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/DL-Simplified#422]
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** : Covid Vaccine Tracker using Deep Learning</br>
:red_circle: **Aim** : Create a DL model to track the Covid-19 vaccine system.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/imdevskp/corona-virus-report</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by VaishnaviMudaliar** [comment]
Full name :
GitHub Profile Link : https://github.com/VaishnaviMudaliar
Email ID : vaishnavim1311@gmail.com
Participant ID (if applicable): https://quine.sh/user/VaishnaviMudaliar
Approach for this Project : 
dataset : https://www.kaggle.com/datasets/imdevskp/corona-virus-report

Steps to approach this problem : 

1 . Data Cleaning & Preprocessing : 
In this step , the data will be preprocessed to eliminate the missing values and outliers . 

2. Data Visualization : 

Some parameters to visualize data are:
- What is the number of cases per state?
- What is the number of deaths in each province due to covid?
- What is the growth in active cases over cases?
-  What is rate of death due to covid over the years?

3 . Model Selection : Since the given data is time series data , we need to employ time series models for this project . In my opinion using ARIMA model for forecasting would be the best . 

4 . Model Evaluation : metrics like root mean squared error can be used to evaluate the model

5. Model Deployment : the model can be deployed as a .pkl file followed by a dedicated api


What is your participant role? SWOC Contributor

**Comment by steve2700** [comment]
can u please assign this to me

**Comment by abhisheks008** [comment]
Issue assigned to you @VaishnaviMudalia. You can start working on it.

**Comment by steve2700** [comment]
Thanks as soon as possible

**Comment by VaishnaviMudaliar** [comment]
> Issue assigned to you @VaishnaviMudalia. You can start working on it.

Thank you very much

**Comment by A-b-i-r-a-m-i-G-S** [comment]
- Full name : Abirami Gurushanker
- GitHub Profile Link : https://github.com/A-b-i-r-a-m-i-G-S
- Email ID : abiramigs21@gmail.com
- Participant ID (if applicable): NA
- Approach for this Project :

  1. Load the dataset.
  2. Understand the dataset by doing extensive EDA.
  3. Clean and preprocess the data.
  4. Use an appropriate model to forecast no. of active cases, no. of deaths, no.of recovered patients, etc. Since this is a time series problem, models like ARIMA, SARIMAX, LSTM, etc can be experimented with.
  5. Present the results of EDA and forecasting in a comprehensive manner in the notebook and README.md files

- What is your participant role? GSSOC'24 contributor

@abhisheks008 I would like to work on this issue. Kindly assign this to me.

**Comment by abhisheks008** [comment]
Assigned to you @A-b-i-r-a-m-i-G-S. You can start working on it.
