### ISSUE TITLE
Realtime Object Detection Project

### ISSUE THREAD

**Issue by ramana2074** [abhisheks008/DL-Simplified#894]
My approach :
Using pretrained model YOLO.
with a certain number of Names (classes/labels)
identify these labels in the image 

@abhisheks008 please assign me this.

**Comment by anniepauline** [comment]
I can work on it

**Comment by abhisheks008** [comment]
Object detection project is already present in this repository.

**Comment by ramana2074** [comment]
![Output](https://github.com/user-attachments/assets/00adbd08-447f-45d9-85d4-703c8e89ec0a)
This would be the output.  projects present in this repository doesn't identify multiple classes objects

**Comment by abhisheks008** [comment]
I'd like to suggest something here. The problem statement is similar, it's kind of an upgraded version of the existing one. It'll be better if you enhance the existing project, rather than going for a separate folder with almost similar problem statement.

Looking forward to hear from you @ramana2074

**Comment by ramana2074** [comment]
May be,I can replace the old one with mine. is that okay @abhisheks008 ?
